import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner";
const poppins = Poppins({ subsets: ["latin"] ,variable: "--font-poppins",weight: ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900']});

export const metadata: Metadata = {
  title: "Vivek Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "max-w-screen-lg h-auto py-12 mx-auto flex justify-center px-4 sm:px-6 md:px-8 lg:px-12 xl:px-16 2xl:px-20",
          poppins.variable
        )}>{children}
        <Toaster />
        </body>
    </html>
  );
}
