import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner";
const poppins = Poppins({ subsets: ["latin"] ,variable: "--font-poppins",weight: ['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900']});

export const metadata: Metadata = {
  title: "Vivek Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(
          "min-h-screen bg-background font-poppins antialiased",
          poppins.variable
        )}>{children}
        <Toaster />
        </body>
    </html>
  );
}
